### ISSUE TITLE
Lỗi ở hàm kiểm tra tài khoản Bus.CheckAccount

### ISSUE THREAD

**Issue by lekhanh1234** [EnvityStudio/QuanLyNhaKho#4]
Vấn đề:
- Lỗi khi đăng nhập

Cách khôi phục lỗi:
- Chạy project
- Lỗi báo ở dòng 29 trong QuanLyNhaKho.BUS.CheckAccount

Cách khắc phục:
- Thay đổi Password thành MatKhau trong phần if else
- Thêm try catch để handle lỗi

**Comment by EnvityStudio** [comment]
seen
please check new version
